-- ============================================================
--  ClothingStore - database schema for Supabase (PostgreSQL)
-- ============================================================
--  Run this script in the Supabase SQL Editor:
--    Dashboard -> SQL Editor -> New query -> paste -> Run
--
--  The application can also create these tables by itself
--  (hibernate.hbm2ddl.auto=update), but running this script in
--  addition seeds the default shop-owner account and adds
--  proper constraints and foreign keys.
-- ============================================================

-- Staff accounts (owner + employees).
-- Named "users" because "user" is a reserved word in PostgreSQL.
create table if not exists users (
    id       varchar(10)  primary key,
    name     varchar(100) not null unique,
    email    varchar(150),
    password varchar(64)  not null,   -- SHA-256 hex digest, never plain text
    role     varchar(20)  not null default 'EMPLOYEE',
    address  varchar(255)
);

create table if not exists customer (
    id      varchar(10)  primary key,
    name    varchar(100) not null,
    email   varchar(150),
    address varchar(255),
    emp_id  varchar(10)  references users (id)
);

create table if not exists supplier (
    id      varchar(10)  primary key,
    name    varchar(100) not null,
    email   varchar(150),
    company varchar(150)
);

create table if not exists product (
    id       varchar(10)  primary key,
    name     varchar(150) not null,
    size     integer      default 0,
    qty      integer      not null default 0 check (qty >= 0),
    category varchar(20),
    price    double precision not null default 0 check (price >= 0),
    sup_id   varchar(10)  references supplier (id)
);

create table if not exists orders (
    id     varchar(10) primary key,
    cus_id varchar(10) references customer (id),
    status varchar(20),
    date   timestamp,
    amount double precision,
    emp_id varchar(10) references users (id)
);

create table if not exists order_details (
    id         bigint generated by default as identity primary key,
    order_id   varchar(10) not null references orders (id),
    product_id varchar(10) not null references product (id),
    qty        integer     not null check (qty > 0),
    unit_price double precision not null
);

-- ------------------------------------------------------------
--  Default shop-owner account
--  username: admin   |   password: admin123  (CHANGE AFTER FIRST LOGIN)
--  The password column stores SHA-256("admin123").
-- ------------------------------------------------------------
insert into users (id, name, email, password, role, address)
values ('U0001', 'admin', 'owner@clothingstore.local',
        '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9',
        'ADMIN', 'Clothing Store HQ')
on conflict (id) do nothing;

-- ------------------------------------------------------------
--  Optional sample data - handy for a first demo.
--  Delete this block if you want to start with an empty shop.
-- ------------------------------------------------------------
insert into supplier (id, name, email, company) values
    ('S0001', 'Nimal Perera', 'nimal@softline.lk', 'Softline Textiles'),
    ('S0002', 'Ayesha Khan',  'ayesha@tinytogs.com', 'Tiny Togs Imports')
on conflict (id) do nothing;

insert into product (id, name, size, qty, category, price, sup_id) values
    ('P0001', 'Cotton T-shirt',     10, 40, 'KIDS',   1490.00, 'S0001'),
    ('P0002', 'Denim Dungarees',     8, 25, 'KIDS',   3250.00, 'S0002'),
    ('P0003', 'Linen Summer Dress', 12, 18, 'LADIES', 4890.00, 'S0001'),
    ('P0004', 'Oxford Shirt',       42, 30, 'GENTS',  3990.00, 'S0001')
on conflict (id) do nothing;
